### ISSUE TITLE
This error occurs when a model is on the list, but will not be triggered when I add a model to the blacklist.

### ISSUE THREAD

**Issue by xdf000** [DIGITALCRIMINALS/UltimaScraper#1004]
**Model's name and my ID I've hidden** [MODEL NAME],[MY USER ID]

The error message is as follows:

`**[MODEL NAME] : Renaming files.
Processing Scraped Messages
  0%|                                                                                                         | 0/992 [00:00<?, ?it/s]Traceback (most recent call last):
  File "W:\onlyfans\OnlyFans-7.6.1\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\USDER1\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\USDER1\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "W:\onlyfans\OnlyFans-7.6.1\start_us.py", line 44, in main
    _api = await USR.start(
  File "W:\onlyfans\OnlyFans-7.6.1\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "W:\onlyfans\OnlyFans-7.6.1\ultima_scraper\ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 53, in __worker
    await job.task
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 195, in prepare_scraper
    await self.process_scraped_content(
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 231, in process_scraped_content
    unrefined_set: list[dict[str, Any]] = await tqdm_asyncio.gather(
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\USDER1\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 64, in media_scraper
    reformat_item = reformat_manager.prepare_reformat(asset)
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_renamer\reformat.py", line 369, in prepare_reformat
    download_path = self.filesystem_manager.get_directory_manager(
  File "C:\Users\USDER1\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-pyd5C_Xs-py3.10\lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 55, in get_directory_manager
    return self.directory_manager_users[user_id]
KeyError: **[MY USER ID]
 12%|███████████▎                                                                                 | 121/992 [00:00<00:00, 1286.18it/s]`

**Comment by kayser26** [comment]
I am having the same issue, could you find a solution? Thanks

**Comment by xdf000** [comment]
use other scrapers now

**Comment by Jakeyy22** [comment]
Blacklist has not worked for ages, I'm still using a build from the 27th Jan to have them working.

I reported the issue back on 2nd Feb on #824

**Comment by kayser26** [comment]
the problem is related to the messages the model sent you, found out that if i delete the chat, the scrapper will work like a charm, i think is related to an emoji or some other character unknown for the script, working now!

**Comment by xdf000** [comment]
> Blacklist has not worked for ages, I'm still using a build from the 27th Jan to have them working.
> 
> I reported the issue back on 2nd Feb on #824

https://github.com/DIGITALCRIMINALS/UltimaScraper#blacklist_name
I use method#1 ,it working

**Comment by xdf000** [comment]
> the problem is related to the messages the model sent you, found out that if i delete the chat, the scrapper will work like a charm, i think is related to an emoji or some other character unknown for the script, working now!

I dare not delete, there are non-paying long video

**Comment by Jakeyy22** [comment]
> > Blacklist has not worked for ages, I'm still using a build from the 27th Jan to have them working.
> > I reported the issue back on 2nd Feb on #824
> 
> https://github.com/DIGITALCRIMINALS/UltimaScraper#blacklist_name I use method#1 ,it working

Just tried, does not work.

**Comment by jgqipzmvakfaj** [comment]
> the problem is related to the messages the model sent you, found out that if i delete the chat, the scrapper will work like a charm, i think is related to an emoji or some other character unknown for the script, working now!

right ,i clear the model message ,it work good
