### ISSUE TITLE
KeyError: 340600631

### ISSUE THREAD

**Issue by god43** [DIGITALCRIMINALS/UltimaScraper#1010]
i am getting a weird error on one model, i think its because of the messages. the old 7.6.1 version will scrape the profile, but does not get all the ppv. thanks.

`Processing Scraped Messages
  0%|                                                                                           | 0/73 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\OnlyFans-ultima\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\OnlyFans-ultima\start_us.py", line 44, in main
    _api = await USR.start(
  File "E:\OnlyFans-ultima\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\OnlyFans-ultima\ultima_scraper\ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 53, in __worker
    await job.task
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 202, in prepare_scraper
    await self.process_scraped_content(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 237, in process_scraped_content
    unrefined_set: list[dict[str, Any]] = await tqdm_asyncio.gather(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 61, in media_scraper
    reformat_item = reformat_manager.prepare_reformat(asset)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_renamer\reformat.py", line 372, in prepare_reformat
    download_path = self.filesystem_manager.get_directory_manager(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-dOa14nUa-py3.10\lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 55, in get_directory_manager
    return self.directory_manager_users[user_id]
KeyError: 340600631
 53%|███████████████████████████████████████████▎                                     | 39/73 [00:00<00:00, 279.42it/s]`

**Comment by djmarioka** [comment]
I'm receiving very similar errors:

![image](https://github.com/DIGITALCRIMINALS/UltimaScraper/assets/81478245/3d8bf2da-9093-44b3-9a81-dc8a68dce076)

Could anybody help us?

Thx.

**Comment by TheMissingPort** [comment]
I'm getting this too

**Comment by xdf000** [comment]
https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/1004

The same problem, I also tried a pure reset, not a legacy of the 7.6.1 version of the problem

**Comment by Prophaniti86** [comment]
I think I have the same error?

Traceback (most recent call last):
File "C:\Users\Matt\Desktop\UltimaScraper-master\start_us.py", line 62, in
asyncio.run(main())
File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
return loop.run_until_complete(main)
File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
return future.result()
File "C:\Users\Matt\Desktop\UltimaScraper-master\start_us.py", line 44, in main
_api = await USR.start(
File "C:\Users\Matt\Desktop\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in start
await self.start_datascraper(datascraper)
File "C:\Users\Matt\Desktop\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 137, in start_datascraper
await datascraper.datascraper.api.job_manager.process_jobs()
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 45, in process_jobs
await asyncio.create_task(self.__worker())
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_api\managers\job_manager\job_manager.py", line 53, in __worker
await job.task
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 202, in prepare_scraper
await self.process_scraped_content(
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 237, in process_scraped_content
unrefined_set: list[dict[str, Any]] = await tqdm_asyncio.gather(
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in gather
res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\tqdm\asyncio.py", line 79, in
res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 571, in _wait_for_one
return f.result() # May raise f.exception().
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
return i, await f
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 61, in media_scraper
reformat_item = reformat_manager.prepare_reformat(asset)
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_renamer\reformat.py", line 372, in prepare_reformat
download_path = self.filesystem_manager.get_directory_manager(
File "C:\Users\Matt\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-yfGR4bq4-py3.10\lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 55, in get_directory_manager
return self.directory_manager_users[user_id]
Keyerror: <My Auth ID>

**Comment by Prophaniti86** [comment]
I turned off paid content and message and it seems to work now. I think it misses some items though

**Comment by twist3dimages** [comment]
same here

**Comment by billmonti2346** [comment]
Well ok, but I want to download my paid content and messages!
> I turned off paid content and message and it seems to work now. I think it misses some items though
> 

Are you saying that paid content and/or messages are working generally now for you, just not for a specific profile?
> EDIT: Seems to crash on a very specific profile now.
