### ISSUE TITLE
ModuleNotFoundError: No module named 'ultima_scraper_collection'

### ISSUE THREAD

**Issue by SchmittyWerber** [DIGITALCRIMINALS/UltimaScraper#1014]
```
PS G:\ISOs\Stuff\UltimaScraper-7.6.1> poetry run python start_us.py
Traceback (most recent call last):
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'
```

All ive done is install poetry and attempt to run the .py file. Im not sure what im supposed to do here?

**Comment by SchmittyWerber** [comment]
```
PS G:\ISOs\Stuff\UltimaScraper-7.6.1> python updater.py

  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at C:\Python\lib\site-packages\poetry\packages\locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
```

**Comment by FarhadMohseni** [comment]
Run 
`poetry install `
and then run the script again

**Comment by SchmittyWerber** [comment]
```
PS G:\ISOs\Stuff\UltimaScraper-7.6.1> poetry install
Creating virtualenv ultima-scraper-ADMmkv8s-py3.10 in C:\Users\david\AppData\Local\pypoetry\Cache\virtualenvs

  RuntimeError

  The lock file is not compatible with the current version of Poetry.
  Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.

  at C:\Python\lib\site-packages\poetry\packages\locker.py:481 in _get_lock_data
      477│                 "Upgrade Poetry to ensure the lock file is read properly or, alternatively, "
      478│                 "regenerate the lock file with the `poetry lock` command."
      479│             )
      480│         elif not lock_version_allowed:
    → 481│             raise RuntimeError(
      482│                 "The lock file is not compatible with the current version of Poetry.\n"
      483│                 "Upgrade Poetry to be able to read the lock file or, alternatively, "
      484│                 "regenerate the lock file with the `poetry lock` command."
      485│             )
```

**Comment by SchmittyWerber** [comment]
i have installed the most recent version of poetry. all i can figure is a previous version is also installed, but the documentation for uninstalling an old version of poetry is non-existent.

**Comment by SchmittyWerber** [comment]
i uninstalled python and started from scratch. after installing poetry as it says on the poetry website, i now get this error.

```
G:\ISOs\Stuff\UltimaScraper-7.6.1>poetry install
'poetry' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by SchmittyWerber** [comment]
```
      PS G:\ISOs\Stuff\UltimaScraper-7.6.1> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\david\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.5.1)
Installing Poetry (1.5.1): Creating environment
Installing Poetry (1.5.1): Installing Poetry
Installing Poetry (1.5.1): Creating script
Installing Poetry (1.5.1): Done

Poetry (1.5.1) is installed now. Great!

To get started you need Poetry's bin directory (C:\Users\david\AppData\Roaming\Python\Scripts) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\david\AppData\Roaming\Python\Scripts\poetry`.

You can test that everything is set up by executing:

`poetry --version`

PS G:\ISOs\Stuff\UltimaScraper-7.6.1> poetry --version
poetry : The term 'poetry' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ poetry --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (poetry:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command poetry was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\poetry". See "get-help about_Command_Precedence" for more details.
PS G:\ISOs\Stuff\UltimaScraper-7.6.1>

```
i really have no clue what im doing wrong?

**Comment by SchmittyWerber** [comment]
Figured it out: i copied the poetry.exe from C:\Users\USERNAME\AppData\Roaming\Python\Scripts to C:\Users\USERNAME\AppData\Local\Programs\Python\Python311\Scripts and it works now

**Comment by Crazylocust** [comment]
I have the same issue, but changing like you did didn't help. it's driving me nuts
