### ISSUE TITLE
Error: Please refresh the page

### ISSUE THREAD

**Issue by lordoffools** [DIGITALCRIMINALS/UltimaScraper#1024]
This started happening this morning (was working fine late last night), perhaps the common data needs to be refreshed?

`Select Site: 0 = onlyfans | 1 = fansly | 2 = starsavn
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Please refresh the page
Archive Completed in 0.01 Minutes
Pausing scraper for 0 seconds.
`
Redoing the auth.json doesn't help.

**Comment by patchcad** [comment]
Same here. Started happening about an hour ago.

**Comment by blackjax696** [comment]
I don't know if it's related, but at the same time that the scrapper stoped to work, a new release of dynamic rules has released.

[5d9a39a](https://github.com/DIGITALCRIMINALS/dynamic-rules/commit/5d9a39acc9418ed5f1e895e247da112fc82daad7)

**Comment by lordoffools** [comment]
Possibly? I thought it was that, actually.

@DIGITALCRIMINALS

**Comment by DIGITALCRIMINALS** [comment]
It's still broken for you?

**Comment by lordoffools** [comment]
> It's still broken for you?

It is, indeed.

**Comment by DIGITALCRIMINALS** [comment]
I reverted it, dunno why it doesn't work for the rest of you

**Comment by patchcad** [comment]
Both sources stopped working now

**Comment by lordoffools** [comment]
I can confirm that it still does not work despite being reverted.

**Comment by patchcad** [comment]
It's working again!

@DIGITALCRIMINALS Bless you for 30 business days!!! 🙏

**Comment by Chromate** [comment]
Still no joy.

**Comment by naodrej** [comment]
It's not working for me.

**Comment by DIGITALCRIMINALS** [comment]
I changed it back to the updated one because the old one wasn't working .-.

It's working for me now

**Comment by meanjoep92** [comment]
Unfortunately, I'm one of many that's still getting the "Please refresh the page" message.

**Comment by DonaldTPP** [comment]
> **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`

I did that and it's still asking me to refresh page.

**Comment by lordoffools** [comment]
Same. I can confirm that I'm still being asked to refresh page.

**Comment by lordoffools** [comment]
Let me know if there's anything I can do to help diagnose why this is working for some and not for others. Happy to help if I can, @DIGITALCRIMINALS

**Comment by naodrej** [comment]
> **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`

Did not work for me

**Comment by blackjax696** [comment]
> > **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
> 
> I did that and it's still asking me to refresh page.

Try to change the URL on /classes/make_settings.py and /apis/api_helper.py files.

All working here now. Thanks @DIGITALCRIMINALS

**Comment by naodrej** [comment]
> > > **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
> > 
> > 
> > I did that and it's still asking me to refresh page.
> 
> Try to change the URL on /classes/make_settings.py and /apis/api_helper.py files.
> 
> All working here now. Thanks @DIGITALCRIMINALS

That did it, working now. Thank you!

**Comment by DonaldTPP** [comment]
> > > **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
> > 
> > 
> > I did that and it's still asking me to refresh page.
> 
> Try to change the URL on /classes/make_settings.py and /apis/api_helper.py files.
> 
> All working here now. Thanks @DIGITALCRIMINALS

Can confirm this version is now working.

**Comment by lordoffools** [comment]
Thank you! I can confirm that changing it in all three locations (.settings/config.json, classes/make_settings.py, and apis/api_helper.py) did the trick!

**Comment by fightcancer2** [comment]
> Thank you! I can confirm that changing it in all three locations (.settings/config.json, classes/make_settings.py, and apis/api_helper.py) did the trick!

Thanks for listing all 3!! Working now.

**Comment by WillScott73** [comment]
None of the above is working for me at all. 

All that I get when doing >poetry run python start_us.py is

Choose Subscriptions: 0 = All |

And choosing that returns nothing. 

I've even pulled down the source again and started from scratch, having first cleared the pypoetry cache.

Any suggestions on what else I can try?

**Comment by drobb0690** [comment]
Thanks, can confirm changing all 3 worked for me.

**Comment by WillScott73** [comment]
Having stepped through the code in VS Code (setting it up to debug with poetry was challenging!) I discovered that somehow the active setting in auth.json had been set to null, somehow. 

So problem solved for me now.

**Comment by DIGITALCRIMINALS** [comment]
> Having stepped through the code in VS Code (setting it up to debug with poetry was challenging!) I discovered that somehow the active setting in auth.json had been set to null, somehow. 
> 
> So problem solved for me now.

Ahh ye, if anyone else wants to do it, I just create a python venv the standard way, and then VSCode auto detects it and asks if you'd like to change it

**Comment by escontreras1** [comment]
Still works, thanks.

**Comment by Fall0n** [comment]
did try the ways that get it fixed. get new error / problem

Type: Profile
Type: Stories
Traceback (most recent call last):
  File "C:\Temp\UltimaScraper-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Temp\UltimaScraper-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Temp\UltimaScraper-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\Temp\UltimaScraper-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Temp\UltimaScraper-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Temp\UltimaScraper-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\Temp\UltimaScraper-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\Temp\UltimaScraper-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\Temp\UltimaScraper-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

**Comment by ezam0000** [comment]
> > > > **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
> > > 
> > > 
> > > I did that and it's still asking me to refresh page.
> > 
> > 
> > Try to change the URL on /classes/make_settings.py and /apis/api_helper.py files.
> > All working here now. Thanks @DIGITALCRIMINALS
> 
> That did it, working now. Thank you!

can you help a brother out ?

**Comment by fyhtma** [comment]
> > > **EDIT:** Got it working! For those of you using an older version, make sure you go to your `.settings\config.json`, and set your "`dynamic_rules_link`" in line 50 to `https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json`
> > 
> > 
> > I did that and it's still asking me to refresh page.
> 
> Try to change the URL on /classes/make_settings.py and /apis/api_helper.py files.
> 
> All working here now. Thanks @DIGITALCRIMINALS

Thank you so much!

**Comment by Fall0n** [comment]
> Guide to solve the issue:
> 
> 1. Use [Visual Studio Code](https://vscode.dev/) to open the folder (web version will do)
> 2. Click the search button (CTRL + SHIFT + F) and paste https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json
> 3. Replace the links with this link (CTRL + ENTER): https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json

Not working that way. Is there a working way?

**Comment by JamboProduction** [comment]
> > Guide to solve the issue:
> > 
> > 1. Use [Visual Studio Code](https://vscode.dev/) to open the folder (web version will do)
> > 2. Click the search button (CTRL + SHIFT + F) and paste https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json
> > 3. Replace the links with this link (CTRL + ENTER): https://raw.githubusercontent.com/DIGITALCRIMINALS/dynamic-rules/main/onlyfans.json
> 
> Not working that way. Is there a other way make it work?

Also didn't worked for me. So I decided to clone repo again and do the replacing thing and now... IT WORKS :)

**Comment by ezam0000** [comment]
Mine broke again, I cloned once again and can’t find that URL to replace it, after initializing with out . Fuck  help

**Comment by deviint** [comment]
> Mine broke again, I cloned once again and can’t find that URL to replace it, after initializing with out . Fuck help

@ezam0000 Use https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json
