### ISSUE TITLE
ValueError: Invalid isoformat string

### ISSUE THREAD

**Issue by pj12321** [DIGITALCRIMINALS/UltimaScraper#1027]
Getting this error while going through choosing media to scrape.

[2023-07-07 23:51:25] Assigning Jobs
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Traceback (most recent call last):
  File "S:\Scraper\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "S:\Scraper\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "S:\Scraper\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "S:\Scraper\ultima_scraper\ultima_scraper.py", line 136, in start_datascraper
    await self.assign_jobs(final_job_user_list)
  File "S:\Scraper\ultima_scraper\ultima_scraper.py", line 195, in assign_jobs
    await metadata_manager.process_legacy_metadata()
  File "C:\Users\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Qxq09gE2-py3.11\Lib\site-packages\ultima_scraper_collection\managers\metadata_manager\metadata_manager.py", line 345, in process_legacy_metadata
    db_manager.import_metadata(self.legacy_content_metadatas)
  File "C:\Users\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Qxq09gE2-py3.11\Lib\site-packages\ultima_scraper_collection\managers\database_manager\connections\sqlite\sqlite_database.py", line 178, in import_metadata
    date_object = datetime.fromisoformat(media_created_at_string)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid isoformat string: '23-09-2020 10:26:16'

**Comment by fightcancer2** [comment]
Same issue.
