### ISSUE TITLE
Key Error after successfully scraping most of the Content. Help?

### ISSUE THREAD

**Issue by ezam0000** [DIGITALCRIMINALS/UltimaScraper#1038]
Traceback (most recent call last):
  File "/Users/ez/Documents/PROJECTS/UltimaScraper/start_us.py", line 62, in <module>
    asyncio.run(main())
  File "/Users/ez/anaconda3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ez/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/ez/Documents/PROJECTS/UltimaScraper/start_us.py", line 44, in main
    _api = await USR.start(
  File "/Users/ez/Documents/PROJECTS/UltimaScraper/ultima_scraper/ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "/Users/ez/Documents/PROJECTS/UltimaScraper/ultima_scraper/ultima_scraper.py", line 137, in start_datascraper
    await datascraper.datascraper.api.job_manager.process_jobs()
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py", line 45, in process_jobs
    await asyncio.create_task(self.__worker())
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py", line 53, in __worker
    await job.task
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 202, in prepare_scraper
    await self.process_scraped_content(
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_collection/modules/module_streamliner.py", line 237, in process_scraped_content
    unrefined_set: list[dict[str, Any]] = await tqdm_asyncio.gather(
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/tqdm/asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "/Users/ez/anaconda3/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/tqdm/asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_collection/managers/datascraper_manager/datascrapers/onlyfans.py", line 61, in media_scraper
    reformat_item = reformat_manager.prepare_reformat(asset)
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_renamer/reformat.py", line 372, in prepare_reformat
    download_path = self.filesystem_manager.get_directory_manager(
  File "/Users/ez/Library/Caches/pypoetry/virtualenvs/ultima-scraper-mpMxmBBI-py3.10/lib/python3.10/site-packages/ultima_scraper_collection/managers/filesystem_manager.py", line 55, in get_directory_manager
    return self.directory_manager_users[user_id]
KeyError: 34867161
 92%|█████████████████████████████████████████████████████████████████████▋      | 155/169 [00:00<00:00, 749.01it/s]
(base) ez@EZ-MacBook-Pro-M2-Max UltimaScraper % 0
<img width="527" alt="Screenshot 2023-07-15 at 1 46 27 AM" src="https://github.com/DIGITALCRIMINALS/UltimaScraper/assets/48105141/f4e5dfd7-ab9b-4a47-9ce6-a5105e23dfb6">

**Comment by BragnarXIX** [comment]
same error, any solution?

**Comment by ezam0000** [comment]
not yet , at least over here On Jul 18, 2023, at 10:19 PM, BragnarXIX ***@***.***> wrote:﻿
same error, any solution?
