### ISSUE TITLE
Did like they say in thread Please refresh the page new error

### ISSUE THREAD

**Issue by P0rr** [DIGITALCRIMINALS/UltimaScraper#1041]
Get this error

Type: Stories
Traceback (most recent call last):
  File "C:\UltimaScraper-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\UltimaScraper-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\UltimaScraper-7.6.1\datascraper\main_datascraper.py", line 94, in start_datascraper
    await main_helper.process_names(
  File "C:\UltimaScraper-7.6.1\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\UltimaScraper-7.6.1\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\UltimaScraper-7.6.1\modules\onlyfans.py", line 784, in prepare_scraper
    highlights = await subscription.get_highlights()
  File "C:\UltimaScraper-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in get_highlights
    results = [create_highlight(x) for x in results]
  File "C:\UltimaScraper-7.6.1\apis\onlyfans\classes\create_user.py", line 270, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "C:\UltimaScraper-7.6.1\apis\onlyfans\classes\create_highlight.py", line 3, in __init__
    [self.id](http://self.id/): int = option.get("id")
AttributeError: 'str' object has no attribute 'get'

help 
How do i use the thread Please refresh the page fix

**Comment by Fall0n** [comment]
I have same problem i hope some one can help
