### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by obversaria** [DIGITALCRIMINALS/UltimaScraper#1057]
Running on Windows 11 under Python 3.11.4.
Similar to #996, but removing the "id": id line did not resolve the issue. 
Setting supported.onlyfans.settings.jobs.scrape.messages to false in the config.json as suggested in #1000 worked but halfway through running it again, it would result in a keyerror. Messages are one of the things I want to back up so disabling it isn't a great workaround.

Traceback (most recent call last):
  File "F:\UltimaScraper-7.9.0\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\UltimaScraper-7.9.0\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "F:\UltimaScraper-7.9.0\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "F:\UltimaScraper-7.9.0\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\justi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-jEPnyq9x-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 109, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\justi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-jEPnyq9x-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 427, in get_chat_users
    chats = await authed.get_chats()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\justi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-jEPnyq9x-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 260, in get_chats
    result["lastMessage"] = create_message(
                            ^^^^^^^^^^^^^^^
  File "C:\Users\justi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-jEPnyq9x-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
                                                       ~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Alexo88** [comment]
`Traceback (most recent call last):
  File "D:\- GITHUB repo\UltimaScraper-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\VKP\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\- GITHUB repo\UltimaScraper-master\start_us.py", line 44, in main
    _api = await USR.start(
  File "D:\- GITHUB repo\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "D:\- GITHUB repo\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
  File "C:\Users\VKP\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-C9JxXxb6-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 109, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
  File "C:\Users\VKP\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-C9JxXxb6-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 427, in get_chat_users
    chats = await authed.get_chats()
  File "C:\Users\VKP\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-C9JxXxb6-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 260, in get_chats
    result["lastMessage"] = create_message(
  File "C:\Users\VKP\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-C9JxXxb6-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
TypeError: 'NoneType' object is not subscriptable`

i have this problem.

**Comment by Tecpulit** [comment]
@22none Can you share what you added? Tried and it doesn't work,

**Comment by 22none** [comment]
> @22none Can you share what you added? Tried and it doesn't work,
I actually don't recommend adding the code anymore. This was really unreliable especially with more models. I think the best solution for now is to set messages and paid_contents to false in the settings. This makes it so you only have to worry about the one model you're trying to scrape at a time. And not all the models. But if you still want to know what code I added to see which model message was erroring out it was this: 


starting at line 15 in 
AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-ZNou5aO8-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py 

I added: 
        # print("______________USER________________")
        # json.dump(option, sys.stdout)
        # print("\n Message \n")
        # print(user.get_username())
        # print("\n")
This is my first time writing in python though. and you still have to run it then it will error out but it will output the last model which should be the problem model. Then you can fix it like I said above.

**Comment by colonic82** [comment]
I also experienced the same problem.
As mentioned by other users, my problem was related to messages: I deleted them all and everything worked great again!
