### ISSUE TITLE
Error line 62

### ISSUE THREAD

**Issue by math1870** [DIGITALCRIMINALS/UltimaScraper#1060]
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_us.py", line 44, in main
    _api = await USR.start(
  File "E:\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, _subscriptions = await datascraper.account_setup(
  File "C:\Users\mathi\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-0AvWnZYd-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 415, in account_setup
    auth.auth_details.email
AttributeError: 'AuthModel' object has no attribute 'auth_details'. Did you mean: 'get_auth_details'?

**Comment by Alexo88** [comment]
i have same problem

**Comment by TheSulak3** [comment]
Try setting auth info with this, I solved it with it
https://github.com/M-rcus/OnlyFans-Cookie-Helper

Also there's an issue when downloading media, some of the content will be missing due to OF backend changes (imo, ig)

**Comment by TheSulak3** [comment]
> Same error here, tried the Cookie helper but nothing changed, the errors are the same.
> 
> I am on Docker installation, if that helps.

Idk about docker, I’m using python and poetry virtual env

**Comment by mbiasetti** [comment]
Happening to me too. Things were working well until about a week or two ago. I started getting issues about user_id not being found in headers, so added a check for the existence of that - but then get the error above. I have an implementation of the login logic in C# that I'm playing with that was working and now no longer is. I wonder if it has to do with the dynamic rules algorithm? My gut says it does, but hard to tell. I'm not a python coder, but I've been tracing through the authentication logic and everything is in place, but still getting a 401. Hope this helps, and sure hope we find a solution! ;)
