### ISSUE TITLE
macOS: (different) issues with both 7.6.1 and 7.9

### ISSUE THREAD

**Issue by marcintosch** [DIGITALCRIMINALS/UltimaScraper#1077]
Hey there, 

until, I dunno, maybe four weeks ago 7.6.1 worked perfectly fine for me, with python 3.10 on latest macOS Ventura 13.5.(1) - but since then I can't get the Scraper to do its job anymore. This is the error message on 7.6.1

`Traceback (most recent call last):
  File "/Volumes/OF/OF761/start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Volumes/OF/OF761/start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "/Volumes/OF/OF761/datascraper/main_datascraper.py", line 67, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/Volumes/OF/OF761/modules/onlyfans.py", line 88, in account_setup
    authed = await auth.login()
  File "/Volumes/OF/OF761/apis/onlyfans/classes/create_auth.py", line 74, in login
    self.session_manager.headers = create_headers(*a)
  File "/Volumes/OF/OF761/apis/onlyfans/classes/extras.py", line 167, in create_headers
    headers.pop(remove_header)
KeyError: 'user_I'd'`

I thought to myself, okay, try it with 7.9 instead and followed the instructions, yet I can't get it to work with poetry, getting this error message:

`Traceback (most recent call last):
  File "/Volumes/OF/OF79/start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "/Volumes/OF/OF79/tests/main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'`

Any solutions for us macOS guys?

Thanks in advance

**Comment by j-ktz** [comment]
I have this issue  too. Also on Mac
