### ISSUE TITLE
No module named ultimascrapper collection

### ISSUE THREAD

**Issue by Crazylocust** [DIGITALCRIMINALS/UltimaScraper#1079]
Hi, I have reinstalled python, poetry etc....
Everytime I have these errors whereas it used to work normally.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\UltimaScraper-master\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "C:\Users\userDesktop\UltimaScraper-master\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
ModuleNotFoundError: No module named 'ultima_scraper_collection'
PS C:\Users\user\Desktop\UltimaScraper-master>

Any idea of how to deal with it?
Thank you

**Comment by KilliK69** [comment]
yes, i am getting the same error too. 
1.i do a fresh installs, python, poetry, scraper, etc. 
2.then i run python updater.py
it gives me the error 
Unable to determine package info for path: path\construct-2.8.8
3.then i rum poetry run python start_us.py
and i get the 'ultimascrapper collection' error

But i tried something else. 
I downloaded the zips from the side projects , they are modules of the scraper from here:
https://github.com/DIGITALCRIMINALS
i extracted the folders with the project's name (UltimaScraperAPI, etc) in the same folder with the scraper. 
i run again the script, i didnt get the original  'ultimascrapper collection' error, but now i am getting a new error:
ModuleNotFoundError: No module named 'aiohttp'

i dont know where we can find that module, if it exists in one of the zips, or somewhere else. and i dont have time for more trial and error. i hope the dev fixes this, from what i have seen it is a problem that exists for months now.

**Comment by Crazylocust** [comment]
I did the exact same thing, ending up with the same error

**Comment by Crazylocust** [comment]
Thank you for now it works! No issues with OF-scraper

**Comment by Lichterflug** [comment]
Hadn't installed it before, because of using the OFScraper, but I get exactly the same errors. Now I have 3 tools and no one is working.
