### ISSUE TITLE
One FIle Downloads Per Session

### ISSUE THREAD

**Issue by graywolfman** [DIGITALCRIMINALS/UltimaScraper#898]
I have my media selection set to "0" so it selects everything by default as suggested in another issue. I also have Max Threads set to 2 - all other settings are default. With or without these settings, my session only downloads one file. If I cancel the download session and relaunch, it downloads one more.

I am running Windows 10 latest build with Python 3.10.10 (64-Bit) and a new install of Poetry. I also updated the script a few moments ago.
![Screenshot 2023-03-14 091304](https://user-images.githubusercontent.com/64859329/225046877-b1c0200c-11d9-417a-aaf3-33e735459b94.jpg)

Exception ignored in: <function _get_module_lock.<locals>.cb at 0x000001AC2B139120>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 204, in cb
KeyboardInterrupt:
Traceback (most recent call last):
  File "D:\Old D\C\NEVER DELETE\DTOP\asdf\OMF 2\start_us.py", line 71, in <module>
    asyncio.run(main())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-TT9LuBJK-py3.10\lib\site-packages\ultima_scraper_collection\managers\download_manager.py", line 47, in download
    await main_helper.format_image(
  File "C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-TT9LuBJK-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 116, in format_image
    from win32_setctime import setctime
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1411, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1544, in find_spec
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
KeyboardInterrupt
^C

**Comment by DIGITALCRIMINALS** [comment]
Are you using proxies and you can try a higher number for max threads

**Comment by graywolfman** [comment]
> Are you using proxies and you can try a higher number for max threads

No proxies; I just set my threads to 10, then -1. Also uninstalled Python 3.10.10 and installed Python 3.10.1 and got the same results. It starts by downloading items from models I no longer subscribe to, not sure if that matters.
