### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by NininDig** [DIGITALCRIMINALS/UltimaScraper#924]
Getting this issue trying to run updater.py.
I'm using the last version. The file subprocess.py does exist in this location.

Traceback (most recent call last):
  File "C:\Users\utilisateur\Downloads\OnlyFans-master\updater.py", line 50, in <module>
    subprocess.run(["poetry", "update"])
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The specified file can not be found

**Comment by zircom22** [comment]
Make sure to add poetry to your path, I was getting the same error. Also may need to do "pip install requests" as it is not installed by default either.
