### ISSUE TITLE
Please help me I couldn't figure out the current problem

### ISSUE THREAD

**Issue by ziha904** [DIGITALCRIMINALS/UltimaScraper#928]
I ran the updater multiple times and I only receive this output

```
Updating dependencies
Resolving dependencies...

Writing lock file

No dependencies to install or update
Script has been updated, exiting in 5 seconds
```
But when I run start_us.py, I receive this error
```
Traceback (most recent call last):
  File "c:\Users\xxxx\Downloads\OnlyFans-7.6.1\start_us.py", line 22, in <module>
    main_test.check_start_up()
  File "c:\Users\xxxx\Downloads\OnlyFans-7.6.1\tests\main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager        
ModuleNotFoundError: No module named 'ultima_scraper_collection'
```

Am I missing something? I already tried enabling windows path using Powershell as Admin. I'm not that good in programming so tell me in detail what to do if you know how to resolve this.

**Comment by jdkjdji** [comment]
Hello, I use mac, so... i don't know if the solution works in windows. but, i'm install in terminal postgresql, and run again  python updater.py  and works...

**Comment by ziha904** [comment]
It still doesn't work. I'll just wait until a new patch is released.

**Comment by jdkjdji** [comment]
Another problem is in line 22. You should give a tab to alineated [main_test.check_start_up()] with the rest code.

**Comment by NumNuts101** [comment]
try running poetry install
if fixed it for me

**Comment by ziha904** [comment]
Already installed poetry. It still doesn't work.



> **[jdkjdji](/jdkjdji) ** c

What do you mean? How can I code it?

**Comment by ziha904** [comment]
Why close this? It's still not solved. The help above didn't help.

**Comment by DIGITALCRIMINALS** [comment]
I literally ran the same instructions on the front page and it worked for me.
