### ISSUE TITLE
Getting tons of error messages after updating to latest commit

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINALS/UltimaScraper#947]
I have no idea what's going on anymore. This is what I get now after updating to the latest commit, which I did by downloading the latest master and overwriting what was in my OnlyFans-master folder:

> C:\Users\username\Desktop\OnlyFans-master>poetry run python start_us.py
> Traceback (most recent call last):
>   File "C:\Users\username\Desktop\OnlyFans-master\start_us.py", line 63, in <module>
>     asyncio.run(main())
>   File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "C:\Users\username\Desktop\OnlyFans-master\start_us.py", line 44, in main
>     api = await USR.start(
>           ^^^^^^^^^^^^^^^^
>   File "C:\Users\username\Desktop\OnlyFans-master\ultima_scraper\ultima_scraper.py", line 49, in start
>     datascraper.filesystem_manager.activate_directory_manager(api_)
>   File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-AHZt6QQm-py3.11\Lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 69, in activate_directory_manager
>     root_metadata_directory = main_helper.check_space(
>                               ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-AHZt6QQm-py3.11\Lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 138, in check_space
>     obj_Disk = disk_usage(str(download_path.parent))
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-AHZt6QQm-py3.11\Lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 49, in disk_usage
>     raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), path)
> FileNotFoundError: [Errno 2] No such file or directory: 'Y:\\'

I've tried running python updater.py multiple times.

**Comment by Nostang3** [comment]
Here are my errors. I tried moving the messages.db from the parent folder into the legacy folder but it either deletes the one in the legacy folder and creates a new one or it moves it from legacy to parent.

`Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.sites\\OnlyFans\\cubbixoxo\\Metadata\\__legacy_metadata__\\Messages.db' -> '.sites\\OnlyFans\\cubbixoxo\\Metadata\\Messages_0.db'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\onlyfans\start_us.py", line 63, in <module>
    asyncio.run(main())
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\onlyfans\start_us.py", line 44, in main
    api = await USR.start(
          ^^^^^^^^^^^^^^^^
  File "d:\onlyfans\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "d:\onlyfans\ultima_scraper\ultima_scraper.py", line 115, in start_datascraper
    await self.assign_jobs(final_job_user_list)
  File "d:\onlyfans\ultima_scraper\ultima_scraper.py", line 173, in assign_jobs
    metadata_manager = MetadataManager(user, filesystem_manager)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-kEvG0rww-py3.11\Lib\site-packages\ultima_scraper_collection\managers\metadata_manager\metadata_manager.py", line 290, in __init__
    self.update_metadata_filepaths()
  File "C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-kEvG0rww-py3.11\Lib\site-packages\ultima_scraper_collection\managers\metadata_manager\metadata_manager.py", line 645, in update_metadata_filepaths
    self.filesystem_manager.move(metadata_filepath, new_m_f)
  File "C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-kEvG0rww-py3.11\Lib\site-packages\ultima_scraper_collection\managers\filesystem_manager.py", line 49, in move
    shutil.move(src, trg)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.sites\\OnlyFans\\cubbixoxo\\Metadata\\__legacy_metadata__\\Messages.db'`

**Comment by DIGITALCRIMINALS** [comment]
rename __legacy_metadata__ to __legacy__

**Comment by CannotTouch** [comment]
Error here too after a fresh install with just the config and auth imported

`
E:\UltimaScraper-master>poetry run python start_us.py
The __settings__\config.json file has been created. Fill in whatever you need to fill in and then press enter when done.

__user_data__\profiles\OnlyFans\default\auth.json has been created. Fill in the relevant details and then press enter to continue.
__user_data__\profiles\Fansly\default\auth.json has been created. Fill in the relevant details and then press enter to continue.
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 203, in request
    result.raise_for_status()
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://onlyfans.com/api2/v2/users/jordannitex')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\UltimaScraper-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\UltimaScraper-master\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "E:\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "E:\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 398, in account_setup
    await datascraper.manage_subscriptions(
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 348, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 157, in get_all_subscriptions
    results = await authed.get_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 360, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 331, in multi
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 245, in get_user
    response = await self.session_manager.json_request(link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 233, in json_request
    response = await self.request(url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-IdHmQS-O-py3.11\Lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 223, in request
    raise Exception(
Exception: Infinite Loop Detected for unhandled status error: 404
`
