### ISSUE TITLE
fansly keyerror filename

### ISSUE THREAD

**Issue by soadwipe** [DIGITALCRIMINALS/UltimaScraper#949]
I keep getting this error every time i try to scrape fansly. I have also tried the latest version of the scraper and it crashes immediately upon opening. not sure what version i am running to be honest. 

Type: Profile
Traceback (most recent call last):
  File "D:\of\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\of\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "D:\of\datascraper\main_datascraper.py", line 156, in start_datascraper
    await main_helper.process_names(
  File "D:\of\helpers\main_helper.py", line 966, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\of\modules\fansly.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\of\modules\fansly.py", line 778, in prepare_scraper
    await profile_scraper(
  File "D:\of\modules\fansly.py", line 290, in profile_scraper
    filename: str = media_options["filename"].replace("..", ".")
KeyError: 'filename'

**Comment by DIGITALCRIMINALS** [comment]
It's not the latest. start_ofd.py isn't even a file anymore. Download latest commit.

**Comment by soadwipe** [comment]
I have tried on the latest comment and it instantly fails to load the program before crashing and closing. 

I unpack the zip and run it. then it does the above
