### ISSUE TITLE
Can't get it to work at all

### ISSUE THREAD

**Issue by El-tra** [DIGITALCRIMINALS/UltimaScraper#954]
Completely uninstalled everything Python- and Poetry-related.
Installed latest Python, installed latest Poetry.

Running "T:\OF\OnlyFans-master>python --version"
gives me: Python 3.11.2

Running "T:\OF\OnlyFans-master>poetry --version"
gives me: Poetry (version 1.4.2)

Looks good, I thought.

Now it gets buggy:

Running "T:\OF\OnlyFans-master>python updater.py" gives
Traceback (most recent call last):
  File "T:\OF\OnlyFans-master\updater.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

After running "poetry install" the above command still doesn't work but I was able to start "poetry run python start_us.py". Unfortunately the next error comes up, immediately after pressing 1 for OnlyFans.

Any idea what might have gone wrong and/or what to do to fix it? I think, as long as update.py doesn't work, it's no surprise that all the rest doesn't work.

**Comment by tedy02** [comment]
what are you running it on?

**Comment by El-tra** [comment]
W10 Professional x64, patched to the latest release. 
Sorry, would have been an important information. :)

**Comment by tedy02** [comment]
I don't remember what fixed it for my pc but I swear this page was what fixed it... idk see if any of it helps https://github.com/DIGITALCRIMINALS/UltimaScraper/blob/master/ultima_scraper/docs/Linux.md

**Comment by ficarra1002** [comment]
You dont have the requests module for python, run 'pip install requests'.

**Comment by El-tra** [comment]
> You dont have the requests module for python, run 'pip install requests'.

Thanks, that fixed the updater.ph issue indeed.
The scraper is still not running, though. Trying to hunt that down now.

**Comment by El-tra** [comment]
That's what I get:

Traceback (most recent call last):
  File "T:\OF\UltimaScraper-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "T:\OF\UltimaScraper-master\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "T:\OF\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "T:\OF\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 398, in account_setup
    await datascraper.manage_subscriptions(
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 348, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 157, in get_all_subscriptions
    results = await authed.get_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 360, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 331, in multi
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 245, in get_user
    response = await self.session_manager.json_request(link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 230, in json_request
    json_resp = await response.json()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\aiohttp\client_reqrep.py", line 1099, in json
    await self.read()
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\aiohttp\client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Z3Mk20al-py3.11\Lib\site-packages\aiohttp\streams.py", line 349, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by CannotTouch** [comment]
> That's what I get:


https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/953

**Comment by El-tra** [comment]
Unfortunately no change with the version released a few minutes ago.

**Comment by El-tra** [comment]
• Updating ultima-scraper-api (1.0.4 -> 1.0.5)
• Updating ultima-scraper-collection (1.0.1 -> 1.0.2)

Still not running. Error messages as shown above. :(

**Comment by El-tra** [comment]
• Updating importlib-metadata (6.5.0 -> 6.5.1)
• Updating ultima-scraper-collection (1.0.2 -> 1.0.3)

Sorry, same.
