### ISSUE TITLE
cannot import name 'AuthDetails' from 'ultima_scraper_api.apis.fansly.classes.extras

### ISSUE THREAD

**Issue by twist3dimages** [DIGITALCRIMINALS/UltimaScraper#957]
I just updated to the latest version and am getting this error. I am using start_us.py not start_ofd.py

> /array/private/github/Onlyfans/venv/bin/python /array/private/github/Onlyfans/start_us.py 
Traceback (most recent call last):
  File "/array/private/github/Onlyfans/start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "/array/private/github/Onlyfans/tests/main_test.py", line 28, in check_start_up
    check_profiles(fsm.settings_directory, fsm.profiles_directory)
  File "/array/private/github/Onlyfans/tests/main_test.py", line 41, in check_profiles
    from ultima_scraper_api.apis.fansly.classes.extras import (
ImportError: cannot import name 'AuthDetails' from 'ultima_scraper_api.apis.fansly.classes.extras' (/array/private/github/Onlyfans/venv/lib/python3.10/site-packages/ultima_scraper_api/apis/fansly/classes/extras.py)

**Comment by twist3dimages** [comment]
I managed to fix it by deleting the venv folder
