### ISSUE TITLE
Multiple Error Messages when starting

### ISSUE THREAD

**Issue by tedy02** [DIGITALCRIMINALS/UltimaScraper#968]
Was working fine now getting these messages on my PC, Linux computer is working fine. I deleted C:\Users\[USERNAME]\AppData\Local\pypoetry\Cache folder and made the updater recreate it but still receiving the error. As far as I know everything is up to date. Any ideas?

Script has been updated, exiting in 5 seconds
PS C:\OnlyFans> poetry run python start_us.py
Traceback (most recent call last):
  File "C:\OnlyFans\start_us.py", line 13, in <module>
    main_test.check_start_up()
  File "C:\OnlyFans\tests\main_test.py", line 27, in check_start_up
    check_config(fsm.settings_directory)
  File "C:\OnlyFans\tests\main_test.py", line 35, in check_config
    json_config, _updated = main_helper.get_config(config_path)
  File "C:\Users\[USERNAME]\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Fb41Yed6-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 187, in get_config
    json_config = import_json(config_path)
  File "C:\Users\[USERNAME]\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Fb41Yed6-py3.10\lib\site-packages\ultima_scraper_api\helpers\main_helper.py", line 171, in import_json
    json_file = orjson.loads(o_file.read())
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

**Comment by ProfessionalHorder** [comment]
Getting something very similar, ending in

orjson.JSONDecodeError: unexpected character: line 101 column 33 (char 2744)
