### ISSUE TITLE
Connection Closed Error

### ISSUE THREAD

**Issue by BenSomner** [DIGITALCRIMINALS/UltimaScraper#981]
I'm not sure where I've gone wrong but even with a fresh install I keep receiving "Connection Closed" at script startup.

> Traceback (most recent call last):
  File "U:\DigitalCriminal\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\Himeros Admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "U:\DigitalCriminal\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "U:\DigitalCriminal\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "U:\DigitalCriminal\ultima_scraper\ultima_scraper.py", line 88, in start_datascraper
    setup, subscriptions = await datascraper.account_setup(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 402, in account_setup
    await datascraper.manage_subscriptions(
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 352, in manage_subscriptions
    results = await self.datascraper.get_all_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_collection\managers\datascraper_manager\datascrapers\onlyfans.py", line 157, in get_all_subscriptions
    results = await authed.get_subscriptions(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 360, in get_subscriptions
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 331, in multi
    results2 = await asyncio.gather(*tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 245, in get_user
    response = await self.session_manager.json_request(link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\ultima_scraper_api\managers\session_manager.py", line 230, in json_request
    json_resp = await response.json()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\aiohttp\client_reqrep.py", line 1099, in json
    await self.read()
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\aiohttp\client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Himeros Admin\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-Xjw9v2dm-py3.11\Lib\site-packages\aiohttp\streams.py", line 349, in read
    raise self._exception
aiohttp.client_exceptions.ClientConnectionError: Connection closed

**Comment by CannotTouch** [comment]
You can find the fix for this here: https://github.com/DIGITALCRIMINALS/UltimaScraper/issues/953#issuecomment-1520712020

**Comment by BenSomner** [comment]
Amazing, thank you.
