### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Cr4zyM0f01** [DIGITALCRIMINALS/UltimaScraper#993]
Hi sorry to bother you guys but I was wondering if someone could help me or point me in the right direction? I'm pretty new to python but I think I have installed UltimaScraper properly as I can see all my subs and stuff but I'm running into a problem when trying to scrape content. When I get to the part asking me what I want to scrape and I choose 2 = Videos hit enter and it comes back again and asks the same question over and over again no matter what I pick also I get a lot of errors when I quit out of it. I don't know if I done something wrong or would it be because I'm not subbed to the onlyfans account any more but its still active for a day or 2 so I can still see all the content. Hopefully someone can help me or point me in the right direction, would really appreciate it.

```
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
4
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Choose Medias: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
Traceback (most recent call last):
  File "C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_c
omplete
    self.run_forever()
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_fore
ver
    super().run_forever()
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever

    self._run_once()
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\deeja_000\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in st
art
    await self.start_datascraper(datascraper)
  File "C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 115, in s
tart_datascraper
    await self.assign_jobs(final_job_user_list)
  File "C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 204, in a
ssign_jobs
    media_options = await self.option_manager.create_option(
  File "C:\Users\deeja_000\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BijVyPc4-py3.10\lib\site-packages\ult
ima_scraper_collection\managers\option_manager.py", line 16, in create_option
    option = await OptionsFormat(items, options_type, auto_choice).formatter()
  File "C:\Users\deeja_000\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BijVyPc4-py3.10\lib\site-packages\ult
ima_scraper_collection\managers\option_manager.py", line 119, in formatter
    final_list = await self.choose_option()
  File "C:\Users\deeja_000\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-BijVyPc4-py3.10\lib\site-packages\ult
ima_scraper_collection\managers\option_manager.py", line 153, in choose_option
    input_value = input().lower()
KeyboardInterrupt
^CPS C:\Users\deeja_000\Desktop\carolinakiss14\UltimaScraper-master>
```

**Comment by estoat** [comment]
I'm also having this issue.

**Comment by estoat** [comment]
Hey when this happened I typed Yes instead of a number and it started working. After that it seems to be working when I type the numbers. Can you confirm if that works for you?

**Comment by god43** [comment]
nope still broken, just endless looping
