### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Javier-bat** [DIGITALCRIMINALS/UltimaScraper#996]
Traceback (most recent call last):
  File "C:\Users\test\Documents\UltimaScraper-master\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\test\Documents\UltimaScraper-master\start_us.py", line 44, in main
    _api = await USR.start(
  File "C:\Users\test\Documents\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "C:\Users\test\Documents\UltimaScraper-master\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-JThEwbE7-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 110, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-JThEwbE7-py3.10\lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 422, in get_chat_users
    chats = await authed.get_chats()
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-JThEwbE7-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 388, in get_chats
    result["lastMessage"] = create_message(
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\ultima-scraper-JThEwbE7-py3.10\lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
TypeError: 'NoneType' object is not subscriptable

Last commit

**Comment by KryleHelps** [comment]
Most likely something with with your auth.json file, after i configured it again i was able to get it fixed.

Also make sure that "aktive:" is not set to NULL

![image](https://github.com/DIGITALCRIMINALS/UltimaScraper/assets/135656424/27c88132-da0c-4085-a5b8-a418b43719cb)

**Comment by Javier-bat** [comment]
> Most likely something with with your auth.json file, after i configured it again i was able to get it fixed.
> 
> Also make sure that "aktive:" is not set to NULL
> 
> ![image](https://user-images.githubusercontent.com/135656424/243645353-27c88132-da0c-4085-a5b8-a418b43719cb.png)

Thx! working now 

Resume: 
The error occurs due to an incorrect format in the cookies. Do not copy and paste cookies.

format:
    "cookie": "auth_id={{auth_id}}; sess={{sess}}; auth_hash=; auth_uniq_{{auth_id}}=; auth_uid_{{auth_id}}=; aws-waf-token=;"

**Comment by Lanneer487** [comment]
I also keep getting the same error and my auth.json is correct

**Comment by SchmittyWerber** [comment]
same issue 

```
PS G:\ISOs\Stuff\UltimaScraper-7.6.1> poetry run python start_us.py
Choose Sites: 0 = All | 1 = OnlyFans | 2 = Fansly
0
Choose Profiles: 0 = All | 1 = default
0
Choose Subscriptions: 0 = All | 1 = lilyraekitty | 2 = nicoleevien | 3 = lindseygroll | 4 = witchkinks | 5 = bassdrip | 6 = morganlefoy | 7 = rolyatistaylor | 8 = lyracr0w0 | 9 = todopokie | 10 = wychbaebifree | 11 = elfsandi | 12 = kiwisunset | 13 = remiremyy | 14 = frankiebunnies | 15 = mtndewer | 16 = onlytalezfree | 17 = neiima | 18 = norafawn | 19 = mags.irl | 20 = downbadcracker | 21 = natashaalana | 22 = sleepyvegan | 23 = egirlshadowx | 24 = its_pyro_kitten | 25 = pyro.kitten | 26 = emily.angellfree | 27 = thelilfox | 28 = tedditerri | 29 = sadgyaru | 30 = leighbunbun | 31 = kornstarbaby
1
Traceback (most recent call last):
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\start_us.py", line 62, in <module>
    asyncio.run(main())
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\start_us.py", line 44, in main
    _api = await USR.start(
           ^^^^^^^^^^^^^^^^
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\ultima_scraper\ultima_scraper.py", line 50, in start
    await self.start_datascraper(datascraper)
  File "G:\ISOs\Stuff\UltimaScraper-7.6.1\ultima_scraper\ultima_scraper.py", line 135, in start_datascraper
    final_job_user_list = await datascraper.configure_datascraper_jobs()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-B6tx9-Ih-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 109, in configure_datascraper_jobs
    chat_users = await self.get_chat_users()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-B6tx9-Ih-py3.11\Lib\site-packages\ultima_scraper_collection\modules\module_streamliner.py", line 427, in get_chat_users
    chats = await authed.get_chats()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-B6tx9-Ih-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\auth_model.py", line 260, in get_chats
    result["lastMessage"] = create_message(
                            ^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\pypoetry\Cache\virtualenvs\ultima-scraper-B6tx9-Ih-py3.11\Lib\site-packages\ultima_scraper_api\apis\onlyfans\classes\message_model.py", line 14, in __init__
    author = user.get_authed().find_user_by_identifier(option["fromUser"]["id"])
                                                       ~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by adelh1de** [comment]
Deleting the first line in the auth.json ("id":id;) fixed it

**Comment by passeee** [comment]
neither fixing cookie formatting nor deleting "id" line fixing the error. only option is to disable scraping messages which is dumb.
